name: Deploy to VPS

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        USER_HASH: ${{ secrets.USER_HASH }}
        EMAIL: ${{ secrets.EMAIL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
        
      - name: Deploy to VPS using deploy.sh
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.IP }} << 'EOF'
          cd ${{ github.event.repository.name }}
          
          # Create .env file with secrets
          cat > .env << EOL
          USER_HASH=${{ secrets.USER_HASH }}
          EMAIL=${{ secrets.EMAIL }}
          EOL
          
          # Pull latest changes
          git pull origin main
          
          # Run deployment script
          chmod +x deploy.sh
          ./deploy.sh
          EOF
